$(function(){
	var html = "";
	html+="<div class='panel'>";
	html+="	<div class='mainbtn'>";
	html+="<div style='float:left;'>";
	html+="<input class='btn' type='button' id='agentLogin_login' value='签入'/>";
	html+="<input class='btn' type='button' id='agentLogin_logout' value='签出'/>";
	html+="<input class='btn' type='button' id='agentCallAnswer' value='应答'/>";
	html+="<input class='btn' type='button' id='agentCallHangup' value='挂机'/>";
	html+="<input class='btn' type='button' id='agentStatusSayIdle' value='示闲'/>";
	html+="<input class='btn' type='button' id='agentStatusSayBusy' value='示忙'/>";
	html+="<input class='btn' type='button' id='agentCallHold' value='保持'/>";
	html+="<input class='btn' type='button' id='agentCallUnHold' value='取消保持' onclick='agentCallOperation_showUnHold();'/>";
/*	html+="<input type='radio' value='0' name='zhuanjie' id='outer' checked='checked'/>";
	html+="<label class='autoAnswer'>外接</label>";
	html+="<input type='radio' value='1' name='zhuanjie' id='inner' onclick='agentCallOperation_refreshWorknoList();'/>";
	html+="<label class='autoAnswer'>内接</label>";
	html+="<input class='input' type='text' placeholder='输入外接号码' id='transferOuter' maxlength='12'/>";
	html+="<select class='select-box' name='transferInner' id='transferInner'>";
	html+="</select>";*/
	html+="<input class='btn' type='button' id='zhuanjie' value='转接' onclick='agentCallOperation_showTransfer();'/>";
	html+="<input class='btn' type='button' id='huiyi' value='会议' onclick='agentCallOperation_showThreeParty();'/>";
	html+="<input class='input comminput' type='text' placeholder='输入外呼号码' id='agentOutCallNum' maxlength='12'/>";
	html+="<input class='commbtn' type='button' id='agentStatusOutCall' value='外呼'/>";
	html+="<span class='autoAnswer'>自动应答：</span>";
	html+="<input type='radio' value='0' name='agentSetting_autoAnswer'/>";
	html+="<label class='autoAnswer'>Yes</label>";
	html+="<input type='radio' value='1' name='agentSetting_autoAnswer' checked='checked'/>";
	html+="<label class='autoAnswer'>No</label>";
	html+="<hr>";
	html+="<table class='state_m1'>";
	html+="<tr>";
	html+="<td width='110'>工号：<span id='workNo'></span></td>";
	html+="<td width='110'>座机：<span id='callId'></span></td>";
	html+="<td width='110'>状态：<span id='workStatus'></span></td>";
	html+="<td width='190'>主叫号码：<span id='caller'></span></td>";
	html+="<td width='190'>被叫号码：<span id='called'></span></td>";
	html+="<td width='160'>通话时长：<span id='callDuration'></span></td>";
	html+="</tr>";
	html+="</table>";
	html+="</div>";
	html+="</div>";
	html+="</div>";
	html+="<input value='' type='hidden' id='agentLogin_agentId'>";
	html+="<input value='' type='hidden' id='agentLogin_password'>";
	html+="<input value='' type='hidden' id='agentLogin_phonenumber'>";
	html+="<input value='' type='hidden' id='winFlag'>";
	html+="<input value='' type='hidden' id='contentData'>";
	html+="<input value='' type='hidden' id='skillgroup'>";
	$("#agentDemo").append(html);
});
